name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate-blueprint:
    runs-on: ubuntu-latest
    name: Blueprint Validation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          pip install PyYAML
          
      - name: Validate Blueprint and Repository
        run: |
          python scripts/validate.py